version: 2.1

orbs:
  builddockerimage: hyperchessbotauthor/builddockerimage@1.0.9

jobs:
  build:
    machine: true

    steps:
      - checkout

      - builddockerimage/build:
          dockeruser: "hyperbotauthor"
          dockerrepo: "hyperbot"
          herokuapp: "hyperbotauthor"
          pushdocker: true
          pushheroku: true

workflows:
  version: 2
  build_and_test:
    jobs:
      - build